### ISSUE TITLE
Where did this Project come from??

### ISSUE THREAD

**Issue by IAFahim** [BushraOnika/Monster-game#1]
So rude. Works on project and keeps to herself only. Did you do the art yourself?

**Comment by BushraOnika** [comment]
Nope I got from internet!!!!!

**Comment by IAFahim** [comment]
You can find good pics from internet!! Shocked. So you can like navigate websites. Allahmadulliah

**Comment by BushraOnika** [comment]
Yes yes good me

**Comment by IAFahim** [comment]
Is your net gone?

**Comment by IAFahim** [comment]
Next class at 10 pm to 11.59 pm. you sleep. On next class, you would do screen share and add features. And I would help
